name: CI

on: [push]

jobs:
  test-7_1:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup PHP 7.1 with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

  test-7_2:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup PHP 7.2 with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

  test-7_3:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup PHP 7.3 with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

  test-7_4:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup PHP 7.4 with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

  test-8_0:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup PHP 8.0 with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
